### ISSUE TITLE
SIT Manager 2.2.2404.2617 occasional resets

### ISSUE THREAD

**Issue by apfaffman** [stayintarkov/SIT.Manager.Avalonia#212]
Periodically, I will lose all configured server bookmarks, username login and password, and game and server install path info. It's as if SIT Manager is freshly installed, though I had configured this information and used it previously. 

Though I have the server component installed, I am not using it. I am currently connecting to a docker instance hosted on another host. 

I think this is the first version of SIT Manager with the server bookmark feature. 

I am still learning how to replicate the issue. Manager-000.log attached. 

[Manager-000.log](https://github.com/stayintarkov/SIT.Manager.Avalonia/files/15138674/Manager-000.log)

**Comment by artehe** [comment]
I think this was fixed in #215, but please feel free to reopen it if I'm wrong

**Comment by Outshynd** [comment]
This is still an issue, at least for me. It is repeatable and I've tracked it down to something about saving a character in a server bookmark. If I have no bookmarked servers, or a bookmarked server but without a character saved to that server yet, everything works fine and serializes on load without issue. However, as soon as my ManagerConfig.json has my character saved in the bookmarked server all settings are wiped. Below is the settings that are saved for a bookmarked server + character, and this causes the settings to be reset on the next load of the Launcher 100% of the time.

```
  "BookmarkedServers": [
    {
      "Address": "http://127.0.0.1:6969",
      "Characters": [
        {
          "Username": "Shynd",
          "Password": "asdf",
          "ProfileID": "662da4a000043eae61b4a3a0",
          "Edition": "Edge of Darkness"
        }
      ]
    }
  ],
```

**Comment by arnobru** [comment]
> This is still an issue, at least for me. 

You are correct. I still experience this issue as well after updating the manager.

**Comment by miwi-fbsd** [comment]
can confirm this problem still exsist.

**Comment by MadBuffoon** [comment]
yeah I am having this issue
